version: 2.1
orbs:
  cypress: cypress-io/cypress@5.0.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint (style + tslint)
          command: |
            npm run style || true
            npm run lint || true
      - run:
          name: Build (production)
          command: npx ng build --configuration production
      - run:
          name: Unit tests (Karma Headless)
          command: |
            $bin = (Get-Command google-chrome,chromium,chrome -ErrorAction SilentlyContinue | Select-Object -First 1).Source
            if (-not $bin) { echo "Chrome binary not found"; exit 1 }
            set CHROME_BIN=$bin
            npx ng test --watch=false --browsers=ChromeHeadless --code-coverage
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: coverage

workflows:
  build-and-test:
    jobs:
      - build_and_test
