version: 2.1
orbs:
  cypress: cypress-io/cypress@5.0.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:22.20-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg --no-install-recommends
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint (style + tslint)
          command: |
            npm run style || true
            npm run lint || true
      - run:
          name: Build (production)
          command: npx ng build --configuration production
      - run:
          name: Unit tests (Karma Headless)
          command: npx ng test --watch=false --browsers=ChromeHeadless --code-coverage
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: coverage

workflows:
  build-and-test:
    jobs:
      - build_and_test
